version: "3.9"
services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - 80:80
  frontend:
    build:
      context: ./frontend
    ports:
      - 8080:8080
